<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $muninicipalities = [
            ['id'=>1,'name'=>'Medellin','department_id'=>5],
            ['id'=>2,'name'=>'Abejorral','department_id'=>5],
            ['id'=>3,'name'=>'Abriaqui','department_id'=>5],
            ['id'=>4,'name'=>'Alejandria','department_id'=>5],
            ['id'=>5,'name'=>'Amaga','department_id'=>5],
            ['id'=>6,'name'=>'Amalfi','department_id'=>5],
            ['id'=>7,'name'=>'Andes','department_id'=>5],
            ['id'=>8,'name'=>'Angelopolis','department_id'=>5],
            ['id'=>9,'name'=>'Angostura','department_id'=>5],
            ['id'=>10,'name'=>'Anori','department_id'=>5],
            ['id'=>11,'name'=>'Santafe De Antioquia','department_id'=>5],
            ['id'=>12,'name'=>'Anza','department_id'=>5],
            ['id'=>13,'name'=>'Apartado','department_id'=>5],
            ['id'=>14,'name'=>'Arboletes','department_id'=>5],
            ['id'=>15,'name'=>'Argelia','department_id'=>5],
            ['id'=>16,'name'=>'Armenia','department_id'=>5],
            ['id'=>17,'name'=>'Barbosa','department_id'=>5],
            ['id'=>18,'name'=>'Belmira','department_id'=>5],
            ['id'=>19,'name'=>'Bello','department_id'=>5],
            ['id'=>20,'name'=>'Betania','department_id'=>5],
            ['id'=>21,'name'=>'Betulia','department_id'=>5],
            ['id'=>22,'name'=>'Ciudad Bolivar','department_id'=>5],
            ['id'=>23,'name'=>'Briceño','department_id'=>5],
            ['id'=>24,'name'=>'Buritica','department_id'=>5],
            ['id'=>25,'name'=>'Caceres','department_id'=>5],
            ['id'=>26,'name'=>'Caicedo','department_id'=>5],
            ['id'=>27,'name'=>'Caldas','department_id'=>5],
            ['id'=>28,'name'=>'Campamento','department_id'=>5],
            ['id'=>29,'name'=>'Cañasgordas','department_id'=>5],
            ['id'=>30,'name'=>'Caracoli','department_id'=>5],
            ['id'=>31,'name'=>'Caramanta','department_id'=>5],
            ['id'=>32,'name'=>'Carepa','department_id'=>5],
            ['id'=>33,'name'=>'El Carmen De Viboral','department_id'=>5],
            ['id'=>34,'name'=>'Carolina','department_id'=>5],
            ['id'=>35,'name'=>'Caucasia','department_id'=>5],
            ['id'=>36,'name'=>'Chigorodo','department_id'=>5],
            ['id'=>37,'name'=>'Cisneros','department_id'=>5],
            ['id'=>38,'name'=>'Cocorna','department_id'=>5],
            ['id'=>39,'name'=>'Concepcion','department_id'=>5],
            ['id'=>40,'name'=>'Concordia','department_id'=>5],
            ['id'=>41,'name'=>'Copacabana','department_id'=>5],
            ['id'=>42,'name'=>'Dabeiba','department_id'=>5],
            ['id'=>43,'name'=>'Don Matias','department_id'=>5],
            ['id'=>44,'name'=>'Ebejico','department_id'=>5],
            ['id'=>45,'name'=>'El Bagre','department_id'=>5],
            ['id'=>46,'name'=>'Entrerrios','department_id'=>5],
            ['id'=>47,'name'=>'Envigado','department_id'=>5],
            ['id'=>48,'name'=>'Fredonia','department_id'=>5],
            ['id'=>49,'name'=>'Frontino','department_id'=>5],
            ['id'=>50,'name'=>'Giraldo','department_id'=>5],
            ['id'=>51,'name'=>'Girardota','department_id'=>5],
            ['id'=>52,'name'=>'Gomez Plata','department_id'=>5],
            ['id'=>53,'name'=>'Granada','department_id'=>5],
            ['id'=>54,'name'=>'Guadalupe','department_id'=>5],
            ['id'=>55,'name'=>'Guarne','department_id'=>5],
            ['id'=>56,'name'=>'Guatape','department_id'=>5],
            ['id'=>57,'name'=>'Heliconia','department_id'=>5],
            ['id'=>58,'name'=>'Hispania','department_id'=>5],
            ['id'=>59,'name'=>'Itagüi','department_id'=>5],
            ['id'=>60,'name'=>'Ituango','department_id'=>5],
            ['id'=>61,'name'=>'Jardin','department_id'=>5],
            ['id'=>62,'name'=>'Jerico','department_id'=>5],
            ['id'=>63,'name'=>'La Ceja','department_id'=>5],
            ['id'=>64,'name'=>'La Estrella','department_id'=>5],
            ['id'=>65,'name'=>'La Pintada','department_id'=>5],
            ['id'=>66,'name'=>'La Union','department_id'=>5],
            ['id'=>67,'name'=>'Liborina','department_id'=>5],
            ['id'=>68,'name'=>'Maceo','department_id'=>5],
            ['id'=>69,'name'=>'Marinilla','department_id'=>5],
            ['id'=>70,'name'=>'Montebello','department_id'=>5],
            ['id'=>71,'name'=>'Murindo','department_id'=>5],
            ['id'=>72,'name'=>'Mutata','department_id'=>5],
            ['id'=>73,'name'=>'Nariño','department_id'=>5],
            ['id'=>74,'name'=>'Necocli','department_id'=>5],
            ['id'=>75,'name'=>'Nechi','department_id'=>5],
            ['id'=>76,'name'=>'Olaya','department_id'=>5],
            ['id'=>77,'name'=>'Peñol','department_id'=>5],
            ['id'=>78,'name'=>'Peque','department_id'=>5],
            ['id'=>79,'name'=>'Pueblorrico','department_id'=>5],
            ['id'=>80,'name'=>'Puerto Berrio','department_id'=>5],
            ['id'=>81,'name'=>'Puerto Nare','department_id'=>5],
            ['id'=>82,'name'=>'Puerto Triunfo','department_id'=>5],
            ['id'=>83,'name'=>'Remedios','department_id'=>5],
            ['id'=>84,'name'=>'Retiro','department_id'=>5],
            ['id'=>85,'name'=>'Rionegro','department_id'=>5],
            ['id'=>86,'name'=>'Sabanalarga','department_id'=>5],
            ['id'=>87,'name'=>'Sabaneta','department_id'=>5],
            ['id'=>88,'name'=>'Salgar','department_id'=>5],
            ['id'=>89,'name'=>'San Andres','department_id'=>5],
            ['id'=>90,'name'=>'San Carlos','department_id'=>5],
            ['id'=>91,'name'=>'San Francisco','department_id'=>5],
            ['id'=>92,'name'=>'San Jeronimo','department_id'=>5],
            ['id'=>93,'name'=>'San Jose De La Montaña','department_id'=>5],
            ['id'=>94,'name'=>'San Juan De Uraba','department_id'=>5],
            ['id'=>95,'name'=>'San Luis','department_id'=>5],
            ['id'=>96,'name'=>'San Pedro','department_id'=>5],
            ['id'=>97,'name'=>'San Pedro De Uraba','department_id'=>5],
            ['id'=>98,'name'=>'San Rafael','department_id'=>5],
            ['id'=>99,'name'=>'San Roque','department_id'=>5],
            ['id'=>100,'name'=>'San Vicente','department_id'=>5],
            ['id'=>101,'name'=>'Santa Barbara','department_id'=>5],
            ['id'=>102,'name'=>'Santa Rosa De Osos','department_id'=>5],
            ['id'=>103,'name'=>'Santo Domingo','department_id'=>5],
            ['id'=>104,'name'=>'El Santuario','department_id'=>5],
            ['id'=>105,'name'=>'Segovia','department_id'=>5],
            ['id'=>106,'name'=>'Sonson','department_id'=>5],
            ['id'=>107,'name'=>'Sopetran','department_id'=>5],
            ['id'=>108,'name'=>'Tamesis','department_id'=>5],
            ['id'=>109,'name'=>'Taraza','department_id'=>5],
            ['id'=>110,'name'=>'Tarso','department_id'=>5],
            ['id'=>111,'name'=>'Titiribi','department_id'=>5],
            ['id'=>112,'name'=>'Toledo','department_id'=>5],
            ['id'=>113,'name'=>'Turbo','department_id'=>5],
            ['id'=>114,'name'=>'Uramita','department_id'=>5],
            ['id'=>115,'name'=>'Urrao','department_id'=>5],
            ['id'=>116,'name'=>'Valdivia','department_id'=>5],
            ['id'=>117,'name'=>'Valparaiso','department_id'=>5],
            ['id'=>118,'name'=>'Vegachi','department_id'=>5],
            ['id'=>119,'name'=>'Venecia','department_id'=>5],
            ['id'=>120,'name'=>'Vigia Del Fuerte','department_id'=>5],
            ['id'=>121,'name'=>'Yali','department_id'=>5],
            ['id'=>122,'name'=>'Yarumal','department_id'=>5],
            ['id'=>123,'name'=>'Yolombo','department_id'=>5],
            ['id'=>124,'name'=>'Yondo','department_id'=>5],
            ['id'=>125,'name'=>'Zaragoza','department_id'=>5],
            ['id'=>126,'name'=>'Barranquilla','department_id'=>8],
            ['id'=>127,'name'=>'Baranoa','department_id'=>8],
            ['id'=>128,'name'=>'Campo De La Cruz','department_id'=>8],
            ['id'=>129,'name'=>'Candelaria','department_id'=>8],
            ['id'=>130,'name'=>'Galapa','department_id'=>8],
            ['id'=>131,'name'=>'Juan De Acosta','department_id'=>8],
            ['id'=>132,'name'=>'Luruaco','department_id'=>8],
            ['id'=>133,'name'=>'Malambo','department_id'=>8],
            ['id'=>134,'name'=>'Manati','department_id'=>8],
            ['id'=>135,'name'=>'Palmar De Varela','department_id'=>8],
            ['id'=>136,'name'=>'Piojo','department_id'=>8],
            ['id'=>137,'name'=>'Polonuevo','department_id'=>8],
            ['id'=>138,'name'=>'Ponedera','department_id'=>8],
            ['id'=>139,'name'=>'Puerto Colombia','department_id'=>8],
            ['id'=>140,'name'=>'Repelon','department_id'=>8],
            ['id'=>141,'name'=>'Sabanagrande','department_id'=>8],
            ['id'=>142,'name'=>'Sabanalarga','department_id'=>8],
            ['id'=>143,'name'=>'Santa Lucia','department_id'=>8],
            ['id'=>144,'name'=>'Santo Tomas','department_id'=>8],
            ['id'=>145,'name'=>'Soledad','department_id'=>8],
            ['id'=>146,'name'=>'Suan','department_id'=>8],
            ['id'=>147,'name'=>'Tubara','department_id'=>8],
            ['id'=>148,'name'=>'Usiacuri','department_id'=>8],
            ['id'=>149,'name'=>'Bogota','department_id'=>11],
            ['id'=>150,'name'=>'Cartagena','department_id'=>13],
            ['id'=>151,'name'=>'Achi','department_id'=>13],
            ['id'=>152,'name'=>'Altos Del Rosario','department_id'=>13],
            ['id'=>153,'name'=>'Arenal','department_id'=>13],
            ['id'=>154,'name'=>'Arjona','department_id'=>13],
            ['id'=>155,'name'=>'Arroyohondo','department_id'=>13],
            ['id'=>156,'name'=>'Barranco De Loba','department_id'=>13],
            ['id'=>157,'name'=>'Calamar','department_id'=>13],
            ['id'=>158,'name'=>'Cantagallo','department_id'=>13],
            ['id'=>159,'name'=>'Cicuco','department_id'=>13],
            ['id'=>160,'name'=>'Cordoba','department_id'=>13],
            ['id'=>161,'name'=>'Clemencia','department_id'=>13],
            ['id'=>162,'name'=>'El Carmen De Bolivar','department_id'=>13],
            ['id'=>163,'name'=>'El Guamo','department_id'=>13],
            ['id'=>164,'name'=>'El Peñon','department_id'=>13],
            ['id'=>165,'name'=>'Hatillo De Loba','department_id'=>13],
            ['id'=>166,'name'=>'Magangue','department_id'=>13],
            ['id'=>167,'name'=>'Mahates','department_id'=>13],
            ['id'=>168,'name'=>'Margarita','department_id'=>13],
            ['id'=>169,'name'=>'Maria La Baja','department_id'=>13],
            ['id'=>170,'name'=>'Montecristo','department_id'=>13],
            ['id'=>171,'name'=>'Mompos','department_id'=>13],
            ['id'=>172,'name'=>'Morales','department_id'=>13],
            ['id'=>173,'name'=>'Pinillos','department_id'=>13],
            ['id'=>174,'name'=>'Regidor','department_id'=>13],
            ['id'=>175,'name'=>'Rio Viejo','department_id'=>13],
            ['id'=>176,'name'=>'San Cristobal','department_id'=>13],
            ['id'=>177,'name'=>'San Estanislao','department_id'=>13],
            ['id'=>178,'name'=>'San Fernando','department_id'=>13],
            ['id'=>179,'name'=>'San Jacinto','department_id'=>13],
            ['id'=>180,'name'=>'San Jacinto Del Cauca','department_id'=>13],
            ['id'=>181,'name'=>'San Juan Nepomuceno','department_id'=>13],
            ['id'=>182,'name'=>'San Martin De Loba','department_id'=>13],
            ['id'=>183,'name'=>'San Pablo','department_id'=>13],
            ['id'=>184,'name'=>'Santa Catalina','department_id'=>13],
            ['id'=>185,'name'=>'Santa Rosa','department_id'=>13],
            ['id'=>186,'name'=>'Santa Rosa Del Sur','department_id'=>13],
            ['id'=>187,'name'=>'Simiti','department_id'=>13],
            ['id'=>188,'name'=>'Soplaviento','department_id'=>13],
            ['id'=>189,'name'=>'Talaigua Nuevo','department_id'=>13],
            ['id'=>190,'name'=>'Tiquisio','department_id'=>13],
            ['id'=>191,'name'=>'Turbaco','department_id'=>13],
            ['id'=>192,'name'=>'Turbana','department_id'=>13],
            ['id'=>193,'name'=>'Villanueva','department_id'=>13],
            ['id'=>194,'name'=>'Zambrano','department_id'=>13],
            ['id'=>195,'name'=>'Tunja','department_id'=>15],
            ['id'=>196,'name'=>'Almeida','department_id'=>15],
            ['id'=>197,'name'=>'Aquitania','department_id'=>15],
            ['id'=>198,'name'=>'Arcabuco','department_id'=>15],
            ['id'=>199,'name'=>'Belen','department_id'=>15],
            ['id'=>200,'name'=>'Berbeo','department_id'=>15],
            ['id'=>201,'name'=>'Beteitiva','department_id'=>15],
            ['id'=>202,'name'=>'Boavita','department_id'=>15],
            ['id'=>203,'name'=>'Boyaca','department_id'=>15],
            ['id'=>204,'name'=>'Briceño','department_id'=>15],
            ['id'=>205,'name'=>'Buenavista','department_id'=>15],
            ['id'=>206,'name'=>'Busbanza','department_id'=>15],
            ['id'=>207,'name'=>'Caldas','department_id'=>15],
            ['id'=>208,'name'=>'Campohermoso','department_id'=>15],
            ['id'=>209,'name'=>'Cerinza','department_id'=>15],
            ['id'=>210,'name'=>'Chinavita','department_id'=>15],
            ['id'=>211,'name'=>'Chiquinquira','department_id'=>15],
            ['id'=>212,'name'=>'Chiscas','department_id'=>15],
            ['id'=>213,'name'=>'Chita','department_id'=>15],
            ['id'=>214,'name'=>'Chitaraque','department_id'=>15],
            ['id'=>215,'name'=>'Chivata','department_id'=>15],
            ['id'=>216,'name'=>'Cienega','department_id'=>15],
            ['id'=>217,'name'=>'Combita','department_id'=>15],
            ['id'=>218,'name'=>'Coper','department_id'=>15],
            ['id'=>219,'name'=>'Corrales','department_id'=>15],
            ['id'=>220,'name'=>'Covarachia','department_id'=>15],
            ['id'=>221,'name'=>'Cubara','department_id'=>15],
            ['id'=>222,'name'=>'Cucaita','department_id'=>15],
            ['id'=>223,'name'=>'Cuitiva','department_id'=>15],
            ['id'=>224,'name'=>'Chiquiza','department_id'=>15],
            ['id'=>225,'name'=>'Chivor','department_id'=>15],
            ['id'=>226,'name'=>'Duitama','department_id'=>15],
            ['id'=>227,'name'=>'El Cocuy','department_id'=>15],
            ['id'=>228,'name'=>'El Espino','department_id'=>15],
            ['id'=>229,'name'=>'Firavitoba','department_id'=>15],
            ['id'=>230,'name'=>'Floresta','department_id'=>15],
            ['id'=>231,'name'=>'Gachantiva','department_id'=>15],
            ['id'=>232,'name'=>'Gameza','department_id'=>15],
            ['id'=>233,'name'=>'Garagoa','department_id'=>15],
            ['id'=>234,'name'=>'Guacamayas','department_id'=>15],
            ['id'=>235,'name'=>'Guateque','department_id'=>15],
            ['id'=>236,'name'=>'Guayata','department_id'=>15],
            ['id'=>237,'name'=>'Güican','department_id'=>15],
            ['id'=>238,'name'=>'Iza','department_id'=>15],
            ['id'=>239,'name'=>'Jenesano','department_id'=>15],
            ['id'=>240,'name'=>'Jerico','department_id'=>15],
            ['id'=>241,'name'=>'Labranzagrande','department_id'=>15],
            ['id'=>242,'name'=>'La Capilla','department_id'=>15],
            ['id'=>243,'name'=>'La Victoria','department_id'=>15],
            ['id'=>244,'name'=>'La Uvita','department_id'=>15],
            ['id'=>245,'name'=>'Villa De Leyva','department_id'=>15],
            ['id'=>246,'name'=>'Macanal','department_id'=>15],
            ['id'=>247,'name'=>'Maripi','department_id'=>15],
            ['id'=>248,'name'=>'Miraflores','department_id'=>15],
            ['id'=>249,'name'=>'Mongua','department_id'=>15],
            ['id'=>250,'name'=>'Mongui','department_id'=>15],
            ['id'=>251,'name'=>'Moniquira','department_id'=>15],
            ['id'=>252,'name'=>'Motavita','department_id'=>15],
            ['id'=>253,'name'=>'Muzo','department_id'=>15],
            ['id'=>254,'name'=>'Nobsa','department_id'=>15],
            ['id'=>255,'name'=>'Nuevo Colon','department_id'=>15],
            ['id'=>256,'name'=>'Oicata','department_id'=>15],
            ['id'=>257,'name'=>'Otanche','department_id'=>15],
            ['id'=>258,'name'=>'Pachavita','department_id'=>15],
            ['id'=>259,'name'=>'Paez','department_id'=>15],
            ['id'=>260,'name'=>'Paipa','department_id'=>15],
            ['id'=>261,'name'=>'Pajarito','department_id'=>15],
            ['id'=>262,'name'=>'Panqueba','department_id'=>15],
            ['id'=>263,'name'=>'Pauna','department_id'=>15],
            ['id'=>264,'name'=>'Paya','department_id'=>15],
            ['id'=>265,'name'=>'Paz De Rio','department_id'=>15],
            ['id'=>266,'name'=>'Pesca','department_id'=>15],
            ['id'=>267,'name'=>'Pisba','department_id'=>15],
            ['id'=>268,'name'=>'Puerto Boyaca','department_id'=>15],
            ['id'=>269,'name'=>'Quipama','department_id'=>15],
            ['id'=>270,'name'=>'Ramiriqui','department_id'=>15],
            ['id'=>271,'name'=>'Raquira','department_id'=>15],
            ['id'=>272,'name'=>'Rondon','department_id'=>15],
            ['id'=>273,'name'=>'Saboya','department_id'=>15],
            ['id'=>274,'name'=>'Sachica','department_id'=>15],
            ['id'=>275,'name'=>'Samaca','department_id'=>15],
            ['id'=>276,'name'=>'San Eduardo','department_id'=>15],
            ['id'=>277,'name'=>'San Jose De Pare','department_id'=>15],
            ['id'=>278,'name'=>'San Luis De Gaceno','department_id'=>15],
            ['id'=>279,'name'=>'San Mateo','department_id'=>15],
            ['id'=>280,'name'=>'San Miguel De Sema','department_id'=>15],
            ['id'=>281,'name'=>'San Pablo De Borbur','department_id'=>15],
            ['id'=>282,'name'=>'Santana','department_id'=>15],
            ['id'=>283,'name'=>'Santa Maria','department_id'=>15],
            ['id'=>284,'name'=>'Santa Rosa De Viterbo','department_id'=>15],
            ['id'=>285,'name'=>'Santa Sofia','department_id'=>15],
            ['id'=>286,'name'=>'Sativanorte','department_id'=>15],
            ['id'=>287,'name'=>'Sativasur','department_id'=>15],
            ['id'=>288,'name'=>'Siachoque','department_id'=>15],
            ['id'=>289,'name'=>'Soata','department_id'=>15],
            ['id'=>290,'name'=>'Socota','department_id'=>15],
            ['id'=>291,'name'=>'Socha','department_id'=>15],
            ['id'=>292,'name'=>'Sogamoso','department_id'=>15],
            ['id'=>293,'name'=>'Somondoco','department_id'=>15],
            ['id'=>294,'name'=>'Sora','department_id'=>15],
            ['id'=>295,'name'=>'Sotaquira','department_id'=>15],
            ['id'=>296,'name'=>'Soraca','department_id'=>15],
            ['id'=>297,'name'=>'Susacon','department_id'=>15],
            ['id'=>298,'name'=>'Sutamarchan','department_id'=>15],
            ['id'=>299,'name'=>'Sutatenza','department_id'=>15],
            ['id'=>300,'name'=>'Tasco','department_id'=>15],
            ['id'=>301,'name'=>'Tenza','department_id'=>15],
            ['id'=>302,'name'=>'Tibana','department_id'=>15],
            ['id'=>303,'name'=>'Tibasosa','department_id'=>15],
            ['id'=>304,'name'=>'Tinjaca','department_id'=>15],
            ['id'=>305,'name'=>'Tipacoque','department_id'=>15],
            ['id'=>306,'name'=>'Toca','department_id'=>15],
            ['id'=>307,'name'=>'Togüi','department_id'=>15],
            ['id'=>308,'name'=>'Topaga','department_id'=>15],
            ['id'=>309,'name'=>'Tota','department_id'=>15],
            ['id'=>310,'name'=>'Tunungua','department_id'=>15],
            ['id'=>311,'name'=>'Turmeque','department_id'=>15],
            ['id'=>312,'name'=>'Tuta','department_id'=>15],
            ['id'=>313,'name'=>'Tutaza','department_id'=>15],
            ['id'=>314,'name'=>'Umbita','department_id'=>15],
            ['id'=>315,'name'=>'Ventaquemada','department_id'=>15],
            ['id'=>316,'name'=>'Viracacha','department_id'=>15],
            ['id'=>317,'name'=>'Zetaquira','department_id'=>15],
            ['id'=>318,'name'=>'Manizales','department_id'=>17],
            ['id'=>319,'name'=>'Aguadas','department_id'=>17],
            ['id'=>320,'name'=>'Anserma','department_id'=>17],
            ['id'=>321,'name'=>'Aranzazu','department_id'=>17],
            ['id'=>322,'name'=>'Belalcazar','department_id'=>17],
            ['id'=>323,'name'=>'Chinchina','department_id'=>17],
            ['id'=>324,'name'=>'Filadelfia','department_id'=>17],
            ['id'=>325,'name'=>'La Dorada','department_id'=>17],
            ['id'=>326,'name'=>'La Merced','department_id'=>17],
            ['id'=>327,'name'=>'Manzanares','department_id'=>17],
            ['id'=>328,'name'=>'Marmato','department_id'=>17],
            ['id'=>329,'name'=>'Marquetalia','department_id'=>17],
            ['id'=>330,'name'=>'Marulanda','department_id'=>17],
            ['id'=>331,'name'=>'Neira','department_id'=>17],
            ['id'=>332,'name'=>'Norcasia','department_id'=>17],
            ['id'=>333,'name'=>'Pacora','department_id'=>17],
            ['id'=>334,'name'=>'Palestina','department_id'=>17],
            ['id'=>335,'name'=>'Pensilvania','department_id'=>17],
            ['id'=>336,'name'=>'Riosucio','department_id'=>17],
            ['id'=>337,'name'=>'Risaralda','department_id'=>17],
            ['id'=>338,'name'=>'Salamina','department_id'=>17],
            ['id'=>339,'name'=>'Samana','department_id'=>17],
            ['id'=>340,'name'=>'San Jose','department_id'=>17],
            ['id'=>341,'name'=>'Supia','department_id'=>17],
            ['id'=>342,'name'=>'Victoria','department_id'=>17],
            ['id'=>343,'name'=>'Villamaria','department_id'=>17],
            ['id'=>344,'name'=>'Viterbo','department_id'=>17],
            ['id'=>345,'name'=>'Florencia','department_id'=>18],
            ['id'=>346,'name'=>'Albania','department_id'=>18],
            ['id'=>347,'name'=>'Belen De Los Andaquies','department_id'=>18],
            ['id'=>348,'name'=>'Cartagena Del Chaira','department_id'=>18],
            ['id'=>349,'name'=>'Curillo','department_id'=>18],
            ['id'=>350,'name'=>'El Doncello','department_id'=>18],
            ['id'=>351,'name'=>'El Paujil','department_id'=>18],
            ['id'=>352,'name'=>'La Montañita','department_id'=>18],
            ['id'=>353,'name'=>'Milan','department_id'=>18],
            ['id'=>354,'name'=>'Morelia','department_id'=>18],
            ['id'=>355,'name'=>'Puerto Rico','department_id'=>18],
            ['id'=>356,'name'=>'San Jose De La Fragua','department_id'=>18],
            ['id'=>357,'name'=>'San Vicente Del Caguan','department_id'=>18],
            ['id'=>358,'name'=>'Solano','department_id'=>18],
            ['id'=>359,'name'=>'Solita','department_id'=>18],
            ['id'=>360,'name'=>'Valparaiso','department_id'=>18],
            ['id'=>361,'name'=>'Popayan','department_id'=>19],
            ['id'=>362,'name'=>'Almaguer','department_id'=>19],
            ['id'=>363,'name'=>'Argelia','department_id'=>19],
            ['id'=>364,'name'=>'Balboa','department_id'=>19],
            ['id'=>365,'name'=>'Bolivar','department_id'=>19],
            ['id'=>366,'name'=>'Buenos Aires','department_id'=>19],
            ['id'=>367,'name'=>'Cajibio','department_id'=>19],
            ['id'=>368,'name'=>'Caldono','department_id'=>19],
            ['id'=>369,'name'=>'Caloto','department_id'=>19],
            ['id'=>370,'name'=>'Corinto','department_id'=>19],
            ['id'=>371,'name'=>'El Tambo','department_id'=>19],
            ['id'=>372,'name'=>'Florencia','department_id'=>19],
            ['id'=>373,'name'=>'Guapi','department_id'=>19],
            ['id'=>374,'name'=>'Inza','department_id'=>19],
            ['id'=>375,'name'=>'Jambalo','department_id'=>19],
            ['id'=>376,'name'=>'La Sierra','department_id'=>19],
            ['id'=>377,'name'=>'La Vega','department_id'=>19],
            ['id'=>378,'name'=>'Lopez','department_id'=>19],
            ['id'=>379,'name'=>'Mercaderes','department_id'=>19],
            ['id'=>380,'name'=>'Miranda','department_id'=>19],
            ['id'=>381,'name'=>'Morales','department_id'=>19],
            ['id'=>382,'name'=>'Padilla','department_id'=>19],
            ['id'=>383,'name'=>'Paez','department_id'=>19],
            ['id'=>384,'name'=>'Patia','department_id'=>19],
            ['id'=>385,'name'=>'Piamonte','department_id'=>19],
            ['id'=>386,'name'=>'Piendamo','department_id'=>19],
            ['id'=>387,'name'=>'Puerto Tejada','department_id'=>19],
            ['id'=>388,'name'=>'Purace','department_id'=>19],
            ['id'=>389,'name'=>'Rosas','department_id'=>19],
            ['id'=>390,'name'=>'San Sebastian','department_id'=>19],
            ['id'=>391,'name'=>'Santander De Quilichao','department_id'=>19],
            ['id'=>392,'name'=>'Santa Rosa','department_id'=>19],
            ['id'=>393,'name'=>'Silvia','department_id'=>19],
            ['id'=>394,'name'=>'Sotara','department_id'=>19],
            ['id'=>395,'name'=>'Suarez','department_id'=>19],
            ['id'=>396,'name'=>'Sucre','department_id'=>19],
            ['id'=>397,'name'=>'Timbio','department_id'=>19],
            ['id'=>398,'name'=>'Timbiqui','department_id'=>19],
            ['id'=>399,'name'=>'Toribio','department_id'=>19],
            ['id'=>400,'name'=>'Totoro','department_id'=>19],
            ['id'=>401,'name'=>'Villa Rica','department_id'=>19],
            ['id'=>402,'name'=>'Valledupar','department_id'=>20],
            ['id'=>403,'name'=>'Aguachica','department_id'=>20],
            ['id'=>404,'name'=>'Agustin Codazzi','department_id'=>20],
            ['id'=>405,'name'=>'Astrea','department_id'=>20],
            ['id'=>406,'name'=>'Becerril','department_id'=>20],
            ['id'=>407,'name'=>'Bosconia','department_id'=>20],
            ['id'=>408,'name'=>'Chimichagua','department_id'=>20],
            ['id'=>409,'name'=>'Chiriguana','department_id'=>20],
            ['id'=>410,'name'=>'Curumani','department_id'=>20],
            ['id'=>411,'name'=>'El Copey','department_id'=>20],
            ['id'=>412,'name'=>'El Paso','department_id'=>20],
            ['id'=>413,'name'=>'Gamarra','department_id'=>20],
            ['id'=>414,'name'=>'Gonzalez','department_id'=>20],
            ['id'=>415,'name'=>'La Gloria','department_id'=>20],
            ['id'=>416,'name'=>'La Jagua De Ibirico','department_id'=>20],
            ['id'=>417,'name'=>'Manaure','department_id'=>20],
            ['id'=>418,'name'=>'Pailitas','department_id'=>20],
            ['id'=>419,'name'=>'Pelaya','department_id'=>20],
            ['id'=>420,'name'=>'Pueblo Bello','department_id'=>20],
            ['id'=>421,'name'=>'Rio De Oro','department_id'=>20],
            ['id'=>422,'name'=>'La Paz','department_id'=>20],
            ['id'=>423,'name'=>'San Alberto','department_id'=>20],
            ['id'=>424,'name'=>'San Diego','department_id'=>20],
            ['id'=>425,'name'=>'San Martin','department_id'=>20],
            ['id'=>426,'name'=>'Tamalameque','department_id'=>20],
            ['id'=>427,'name'=>'Monteria','department_id'=>23],
            ['id'=>428,'name'=>'Ayapel','department_id'=>23],
            ['id'=>429,'name'=>'Buenavista','department_id'=>23],
            ['id'=>430,'name'=>'Canalete','department_id'=>23],
            ['id'=>431,'name'=>'Cerete','department_id'=>23],
            ['id'=>432,'name'=>'Chima','department_id'=>23],
            ['id'=>433,'name'=>'Chinu','department_id'=>23],
            ['id'=>434,'name'=>'Cienaga De Oro','department_id'=>23],
            ['id'=>435,'name'=>'Cotorra','department_id'=>23],
            ['id'=>436,'name'=>'La Apartada','department_id'=>23],
            ['id'=>437,'name'=>'Lorica','department_id'=>23],
            ['id'=>438,'name'=>'Los Cordobas','department_id'=>23],
            ['id'=>439,'name'=>'Momil','department_id'=>23],
            ['id'=>440,'name'=>'Montelibano','department_id'=>23],
            ['id'=>441,'name'=>'Moñitos','department_id'=>23],
            ['id'=>442,'name'=>'Planeta Rica','department_id'=>23],
            ['id'=>443,'name'=>'Pueblo Nuevo','department_id'=>23],
            ['id'=>444,'name'=>'Puerto Escondido','department_id'=>23],
            ['id'=>445,'name'=>'Puerto Libertador','department_id'=>23],
            ['id'=>446,'name'=>'Purisima','department_id'=>23],
            ['id'=>447,'name'=>'Sahagun','department_id'=>23],
            ['id'=>448,'name'=>'San Andres De Sotavento','department_id'=>23],
            ['id'=>449,'name'=>'San Antero','department_id'=>23],
            ['id'=>450,'name'=>'San Bernardo Del Viento','department_id'=>23],
            ['id'=>451,'name'=>'San Carlos','department_id'=>23],
            ['id'=>452,'name'=>'San Pelayo','department_id'=>23],
            ['id'=>453,'name'=>'Tierralta','department_id'=>23],
            ['id'=>454,'name'=>'Valencia','department_id'=>23],
            ['id'=>455,'name'=>'Agua De Dios','department_id'=>25],
            ['id'=>456,'name'=>'Alban','department_id'=>25],
            ['id'=>457,'name'=>'Anapoima','department_id'=>25],
            ['id'=>458,'name'=>'Anolaima','department_id'=>25],
            ['id'=>459,'name'=>'Arbelaez','department_id'=>25],
            ['id'=>460,'name'=>'Beltran','department_id'=>25],
            ['id'=>461,'name'=>'Bituima','department_id'=>25],
            ['id'=>462,'name'=>'Bojaca','department_id'=>25],
            ['id'=>463,'name'=>'Cabrera','department_id'=>25],
            ['id'=>464,'name'=>'Cachipay','department_id'=>25],
            ['id'=>465,'name'=>'Cajica','department_id'=>25],
            ['id'=>466,'name'=>'Caparrapi','department_id'=>25],
            ['id'=>467,'name'=>'Caqueza','department_id'=>25],
            ['id'=>468,'name'=>'Carmen De Carupa','department_id'=>25],
            ['id'=>469,'name'=>'Chaguani','department_id'=>25],
            ['id'=>470,'name'=>'Chia','department_id'=>25],
            ['id'=>471,'name'=>'Chipaque','department_id'=>25],
            ['id'=>472,'name'=>'Choachi','department_id'=>25],
            ['id'=>473,'name'=>'Choconta','department_id'=>25],
            ['id'=>474,'name'=>'Cogua','department_id'=>25],
            ['id'=>475,'name'=>'Cota','department_id'=>25],
            ['id'=>476,'name'=>'Cucunuba','department_id'=>25],
            ['id'=>477,'name'=>'El Colegio','department_id'=>25],
            ['id'=>478,'name'=>'El Peñon','department_id'=>25],
            ['id'=>479,'name'=>'El Rosal','department_id'=>25],
            ['id'=>480,'name'=>'Facatativa','department_id'=>25],
            ['id'=>481,'name'=>'Fomeque','department_id'=>25],
            ['id'=>482,'name'=>'Fosca','department_id'=>25],
            ['id'=>483,'name'=>'Funza','department_id'=>25],
            ['id'=>484,'name'=>'Fuquene','department_id'=>25],
            ['id'=>485,'name'=>'Fusagasuga','department_id'=>25],
            ['id'=>486,'name'=>'Gachala','department_id'=>25],
            ['id'=>487,'name'=>'Gachancipa','department_id'=>25],
            ['id'=>488,'name'=>'Gacheta','department_id'=>25],
            ['id'=>489,'name'=>'Gama','department_id'=>25],
            ['id'=>490,'name'=>'Girardot','department_id'=>25],
            ['id'=>491,'name'=>'Granada','department_id'=>25],
            ['id'=>492,'name'=>'Guacheta','department_id'=>25],
            ['id'=>493,'name'=>'Guaduas','department_id'=>25],
            ['id'=>494,'name'=>'Guasca','department_id'=>25],
            ['id'=>495,'name'=>'Guataqui','department_id'=>25],
            ['id'=>496,'name'=>'Guatavita','department_id'=>25],
            ['id'=>497,'name'=>'Guayabal De Siquima','department_id'=>25],
            ['id'=>498,'name'=>'Guayabetal','department_id'=>25],
            ['id'=>499,'name'=>'Gutierrez','department_id'=>25],
            ['id'=>500,'name'=>'Jerusalen','department_id'=>25],
            ['id'=>501,'name'=>'Junin','department_id'=>25],
            ['id'=>502,'name'=>'La Calera','department_id'=>25],
            ['id'=>503,'name'=>'La Mesa','department_id'=>25],
            ['id'=>504,'name'=>'La Palma','department_id'=>25],
            ['id'=>505,'name'=>'La Peña','department_id'=>25],
            ['id'=>506,'name'=>'La Vega','department_id'=>25],
            ['id'=>507,'name'=>'Lenguazaque','department_id'=>25],
            ['id'=>508,'name'=>'Macheta','department_id'=>25],
            ['id'=>509,'name'=>'Madrid','department_id'=>25],
            ['id'=>510,'name'=>'Manta','department_id'=>25],
            ['id'=>511,'name'=>'Medina','department_id'=>25],
            ['id'=>512,'name'=>'Mosquera','department_id'=>25],
            ['id'=>513,'name'=>'Nariño','department_id'=>25],
            ['id'=>514,'name'=>'Nemocon','department_id'=>25],
            ['id'=>515,'name'=>'Nilo','department_id'=>25],
            ['id'=>516,'name'=>'Nimaima','department_id'=>25],
            ['id'=>517,'name'=>'Nocaima','department_id'=>25],
            ['id'=>518,'name'=>'Venecia','department_id'=>25],
            ['id'=>519,'name'=>'Pacho','department_id'=>25],
            ['id'=>520,'name'=>'Paime','department_id'=>25],
            ['id'=>521,'name'=>'Pandi','department_id'=>25],
            ['id'=>522,'name'=>'Paratebueno','department_id'=>25],
            ['id'=>523,'name'=>'Pasca','department_id'=>25],
            ['id'=>524,'name'=>'Puerto Salgar','department_id'=>25],
            ['id'=>525,'name'=>'Puli','department_id'=>25],
            ['id'=>526,'name'=>'Quebradanegra','department_id'=>25],
            ['id'=>527,'name'=>'Quetame','department_id'=>25],
            ['id'=>528,'name'=>'Quipile','department_id'=>25],
            ['id'=>529,'name'=>'Apulo','department_id'=>25],
            ['id'=>530,'name'=>'Ricaurte','department_id'=>25],
            ['id'=>531,'name'=>'San Antonio Del Tequendama','department_id'=>25],
            ['id'=>532,'name'=>'San Bernardo','department_id'=>25],
            ['id'=>533,'name'=>'San Cayetano','department_id'=>25],
            ['id'=>534,'name'=>'San Francisco','department_id'=>25],
            ['id'=>535,'name'=>'San Juan De Rio Seco','department_id'=>25],
            ['id'=>536,'name'=>'Sasaima','department_id'=>25],
            ['id'=>537,'name'=>'Sesquile','department_id'=>25],
            ['id'=>538,'name'=>'Sibate','department_id'=>25],
            ['id'=>539,'name'=>'Silvania','department_id'=>25],
            ['id'=>540,'name'=>'Simijaca','department_id'=>25],
            ['id'=>541,'name'=>'Soacha','department_id'=>25],
            ['id'=>542,'name'=>'Sopo','department_id'=>25],
            ['id'=>543,'name'=>'Subachoque','department_id'=>25],
            ['id'=>544,'name'=>'Suesca','department_id'=>25],
            ['id'=>545,'name'=>'Supata','department_id'=>25],
            ['id'=>546,'name'=>'Susa','department_id'=>25],
            ['id'=>547,'name'=>'Sutatausa','department_id'=>25],
            ['id'=>548,'name'=>'Tabio','department_id'=>25],
            ['id'=>549,'name'=>'Tausa','department_id'=>25],
            ['id'=>550,'name'=>'Tena','department_id'=>25],
            ['id'=>551,'name'=>'Tenjo','department_id'=>25],
            ['id'=>552,'name'=>'Tibacuy','department_id'=>25],
            ['id'=>553,'name'=>'Tibirita','department_id'=>25],
            ['id'=>554,'name'=>'Tocaima','department_id'=>25],
            ['id'=>555,'name'=>'Tocancipa','department_id'=>25],
            ['id'=>556,'name'=>'Topaipi','department_id'=>25],
            ['id'=>557,'name'=>'Ubala','department_id'=>25],
            ['id'=>558,'name'=>'Ubaque','department_id'=>25],
            ['id'=>559,'name'=>'Villa De San Diego De Ubate','department_id'=>25],
            ['id'=>560,'name'=>'Une','department_id'=>25],
            ['id'=>561,'name'=>'Utica','department_id'=>25],
            ['id'=>562,'name'=>'Vergara','department_id'=>25],
            ['id'=>563,'name'=>'Viani','department_id'=>25],
            ['id'=>564,'name'=>'Villagomez','department_id'=>25],
            ['id'=>565,'name'=>'Villapinzon','department_id'=>25],
            ['id'=>566,'name'=>'Villeta','department_id'=>25],
            ['id'=>567,'name'=>'Viota','department_id'=>25],
            ['id'=>568,'name'=>'Yacopi','department_id'=>25],
            ['id'=>569,'name'=>'Zipacon','department_id'=>25],
            ['id'=>570,'name'=>'Zipaquira','department_id'=>25],
            ['id'=>571,'name'=>'Quibdo','department_id'=>27],
            ['id'=>572,'name'=>'Acandi','department_id'=>27],
            ['id'=>573,'name'=>'Alto Baudo','department_id'=>27],
            ['id'=>574,'name'=>'Atrato','department_id'=>27],
            ['id'=>575,'name'=>'Bagado','department_id'=>27],
            ['id'=>576,'name'=>'Bahia Solano','department_id'=>27],
            ['id'=>577,'name'=>'Bajo Baudo','department_id'=>27],
            ['id'=>578,'name'=>'Belen De Bajira','department_id'=>27],
            ['id'=>579,'name'=>'Bojaya','department_id'=>27],
            ['id'=>580,'name'=>'El Canton Del San Pablo','department_id'=>27],
            ['id'=>581,'name'=>'Carmen Del Darien','department_id'=>27],
            ['id'=>582,'name'=>'Certegui','department_id'=>27],
            ['id'=>583,'name'=>'Condoto','department_id'=>27],
            ['id'=>584,'name'=>'El Carmen De Atrato','department_id'=>27],
            ['id'=>585,'name'=>'El Litoral Del San Juan','department_id'=>27],
            ['id'=>586,'name'=>'Istmina','department_id'=>27],
            ['id'=>587,'name'=>'Jurado','department_id'=>27],
            ['id'=>588,'name'=>'Lloro','department_id'=>27],
            ['id'=>589,'name'=>'Medio Atrato','department_id'=>27],
            ['id'=>590,'name'=>'Medio Baudo','department_id'=>27],
            ['id'=>591,'name'=>'Medio San Juan','department_id'=>27],
            ['id'=>592,'name'=>'Novita','department_id'=>27],
            ['id'=>593,'name'=>'Nuqui','department_id'=>27],
            ['id'=>594,'name'=>'Rio Iro','department_id'=>27],
            ['id'=>595,'name'=>'Rio Quito','department_id'=>27],
            ['id'=>596,'name'=>'Riosucio','department_id'=>27],
            ['id'=>597,'name'=>'San Jose Del Palmar','department_id'=>27],
            ['id'=>598,'name'=>'Sipi','department_id'=>27],
            ['id'=>599,'name'=>'Tado','department_id'=>27],
            ['id'=>600,'name'=>'Unguia','department_id'=>27],
            ['id'=>601,'name'=>'Union Panamericana','department_id'=>27],
            ['id'=>602,'name'=>'Neiva','department_id'=>41],
            ['id'=>603,'name'=>'Acevedo','department_id'=>41],
            ['id'=>604,'name'=>'Agrado','department_id'=>41],
            ['id'=>605,'name'=>'Aipe','department_id'=>41],
            ['id'=>606,'name'=>'Algeciras','department_id'=>41],
            ['id'=>607,'name'=>'Altamira','department_id'=>41],
            ['id'=>608,'name'=>'Baraya','department_id'=>41],
            ['id'=>609,'name'=>'Campoalegre','department_id'=>41],
            ['id'=>610,'name'=>'Colombia','department_id'=>41],
            ['id'=>611,'name'=>'Elias','department_id'=>41],
            ['id'=>612,'name'=>'Garzon','department_id'=>41],
            ['id'=>613,'name'=>'Gigante','department_id'=>41],
            ['id'=>614,'name'=>'Guadalupe','department_id'=>41],
            ['id'=>615,'name'=>'Hobo','department_id'=>41],
            ['id'=>616,'name'=>'Iquira','department_id'=>41],
            ['id'=>617,'name'=>'Isnos','department_id'=>41],
            ['id'=>618,'name'=>'La Argentina','department_id'=>41],
            ['id'=>619,'name'=>'La Plata','department_id'=>41],
            ['id'=>620,'name'=>'Nataga','department_id'=>41],
            ['id'=>621,'name'=>'Oporapa','department_id'=>41],
            ['id'=>622,'name'=>'Paicol','department_id'=>41],
            ['id'=>623,'name'=>'Palermo','department_id'=>41],
            ['id'=>624,'name'=>'Palestina','department_id'=>41],
            ['id'=>625,'name'=>'Pital','department_id'=>41],
            ['id'=>626,'name'=>'Pitalito','department_id'=>41],
            ['id'=>627,'name'=>'Rivera','department_id'=>41],
            ['id'=>628,'name'=>'Saladoblanco','department_id'=>41],
            ['id'=>629,'name'=>'San Agustin','department_id'=>41],
            ['id'=>630,'name'=>'Santa Maria','department_id'=>41],
            ['id'=>631,'name'=>'Suaza','department_id'=>41],
            ['id'=>632,'name'=>'Tarqui','department_id'=>41],
            ['id'=>633,'name'=>'Tesalia','department_id'=>41],
            ['id'=>634,'name'=>'Tello','department_id'=>41],
            ['id'=>635,'name'=>'Teruel','department_id'=>41],
            ['id'=>636,'name'=>'Timana','department_id'=>41],
            ['id'=>637,'name'=>'Villavieja','department_id'=>41],
            ['id'=>638,'name'=>'Yaguara','department_id'=>41],
            ['id'=>639,'name'=>'Riohacha','department_id'=>44],
            ['id'=>640,'name'=>'Albania','department_id'=>44],
            ['id'=>641,'name'=>'Barrancas','department_id'=>44],
            ['id'=>642,'name'=>'Dibulla','department_id'=>44],
            ['id'=>643,'name'=>'Distraccion','department_id'=>44],
            ['id'=>644,'name'=>'El Molino','department_id'=>44],
            ['id'=>645,'name'=>'Fonseca','department_id'=>44],
            ['id'=>646,'name'=>'Hatonuevo','department_id'=>44],
            ['id'=>647,'name'=>'La Jagua Del Pilar','department_id'=>44],
            ['id'=>648,'name'=>'Maicao','department_id'=>44],
            ['id'=>649,'name'=>'Manaure','department_id'=>44],
            ['id'=>650,'name'=>'San Juan Del Cesar','department_id'=>44],
            ['id'=>651,'name'=>'Uribia','department_id'=>44],
            ['id'=>652,'name'=>'Urumita','department_id'=>44],
            ['id'=>653,'name'=>'Villanueva','department_id'=>44],
            ['id'=>654,'name'=>'Santa Marta','department_id'=>47],
            ['id'=>655,'name'=>'Algarrobo','department_id'=>47],
            ['id'=>656,'name'=>'Aracataca','department_id'=>47],
            ['id'=>657,'name'=>'Ariguani','department_id'=>47],
            ['id'=>658,'name'=>'Cerro San Antonio','department_id'=>47],
            ['id'=>659,'name'=>'Chivolo','department_id'=>47],
            ['id'=>660,'name'=>'Cienaga','department_id'=>47],
            ['id'=>661,'name'=>'Concordia','department_id'=>47],
            ['id'=>662,'name'=>'El Banco','department_id'=>47],
            ['id'=>663,'name'=>'El Piñon','department_id'=>47],
            ['id'=>664,'name'=>'El Reten','department_id'=>47],
            ['id'=>665,'name'=>'Fundacion','department_id'=>47],
            ['id'=>666,'name'=>'Guamal','department_id'=>47],
            ['id'=>667,'name'=>'Nueva Granada','department_id'=>47],
            ['id'=>668,'name'=>'Pedraza','department_id'=>47],
            ['id'=>669,'name'=>'Pijiño Del Carmen','department_id'=>47],
            ['id'=>670,'name'=>'Pivijay','department_id'=>47],
            ['id'=>671,'name'=>'Plato','department_id'=>47],
            ['id'=>672,'name'=>'Puebloviejo','department_id'=>47],
            ['id'=>673,'name'=>'Remolino','department_id'=>47],
            ['id'=>674,'name'=>'Sabanas De San Angel','department_id'=>47],
            ['id'=>675,'name'=>'Salamina','department_id'=>47],
            ['id'=>676,'name'=>'San Sebastia','department_id'=>47],
            ['id'=>677,'name'=>'San Zenon','department_id'=>47],
            ['id'=>678,'name'=>'Santa Ana','department_id'=>47],
            ['id'=>679,'name'=>'Santa Barbara De Pinto','department_id'=>47],
            ['id'=>680,'name'=>'Sitionuevo','department_id'=>47],
            ['id'=>681,'name'=>'Tenerife','department_id'=>47],
            ['id'=>682,'name'=>'Zapayan','department_id'=>47],
            ['id'=>683,'name'=>'Zona Bananera','department_id'=>47],
            ['id'=>684,'name'=>'Villavicencio','department_id'=>50],
            ['id'=>685,'name'=>'Acacias','department_id'=>50],
            ['id'=>686,'name'=>'Barranca De Upia','department_id'=>50],
            ['id'=>687,'name'=>'Cabuyaro','department_id'=>50],
            ['id'=>688,'name'=>'Castilla La Nueva','department_id'=>50],
            ['id'=>689,'name'=>'Cubarral','department_id'=>50],
            ['id'=>690,'name'=>'Cumaral','department_id'=>50],
            ['id'=>691,'name'=>'El Calvario','department_id'=>50],
            ['id'=>692,'name'=>'El Castillo','department_id'=>50],
            ['id'=>693,'name'=>'El Dorado','department_id'=>50],
            ['id'=>694,'name'=>'Fuente De Oro','department_id'=>50],
            ['id'=>695,'name'=>'Granada','department_id'=>50],
            ['id'=>696,'name'=>'Guamal','department_id'=>50],
            ['id'=>697,'name'=>'Mapiripan','department_id'=>50],
            ['id'=>698,'name'=>'Mesetas','department_id'=>50],
            ['id'=>699,'name'=>'La Macarena','department_id'=>50],
            ['id'=>700,'name'=>'Uribe','department_id'=>50],
            ['id'=>701,'name'=>'Lejanias','department_id'=>50],
            ['id'=>702,'name'=>'Puerto Concordia','department_id'=>50],
            ['id'=>703,'name'=>'Puerto Gaitan','department_id'=>50],
            ['id'=>704,'name'=>'Puerto Lopez','department_id'=>50],
            ['id'=>705,'name'=>'Puerto Lleras','department_id'=>50],
            ['id'=>706,'name'=>'Puerto Rico','department_id'=>50],
            ['id'=>707,'name'=>'Restrepo','department_id'=>50],
            ['id'=>708,'name'=>'San Carlos De Guaroa','department_id'=>50],
            ['id'=>709,'name'=>'San Juan De Arama','department_id'=>50],
            ['id'=>710,'name'=>'San Juanito','department_id'=>50],
            ['id'=>711,'name'=>'San Martin','department_id'=>50],
            ['id'=>712,'name'=>'Vista Hermosa','department_id'=>50],
            ['id'=>713,'name'=>'Pasto','department_id'=>52],
            ['id'=>714,'name'=>'Alban','department_id'=>52],
            ['id'=>715,'name'=>'Aldana','department_id'=>52],
            ['id'=>716,'name'=>'Ancuya','department_id'=>52],
            ['id'=>717,'name'=>'Arboleda','department_id'=>52],
            ['id'=>718,'name'=>'Barbacoas','department_id'=>52],
            ['id'=>719,'name'=>'Belen','department_id'=>52],
            ['id'=>720,'name'=>'Buesaco','department_id'=>52],
            ['id'=>721,'name'=>'Colon','department_id'=>52],
            ['id'=>722,'name'=>'Consaca','department_id'=>52],
            ['id'=>723,'name'=>'Contadero','department_id'=>52],
            ['id'=>724,'name'=>'Cordoba','department_id'=>52],
            ['id'=>725,'name'=>'Cuaspud','department_id'=>52],
            ['id'=>726,'name'=>'Cumbal','department_id'=>52],
            ['id'=>727,'name'=>'Cumbitara','department_id'=>52],
            ['id'=>728,'name'=>'Chachagüi','department_id'=>52],
            ['id'=>729,'name'=>'El Charco','department_id'=>52],
            ['id'=>730,'name'=>'El Peñol','department_id'=>52],
            ['id'=>731,'name'=>'El Rosario','department_id'=>52],
            ['id'=>732,'name'=>'El Tablon De Gomez','department_id'=>52],
            ['id'=>733,'name'=>'El Tambo','department_id'=>52],
            ['id'=>734,'name'=>'Funes','department_id'=>52],
            ['id'=>735,'name'=>'Guachucal','department_id'=>52],
            ['id'=>736,'name'=>'Guaitarilla','department_id'=>52],
            ['id'=>737,'name'=>'Gualmatan','department_id'=>52],
            ['id'=>738,'name'=>'Iles','department_id'=>52],
            ['id'=>739,'name'=>'Imues','department_id'=>52],
            ['id'=>740,'name'=>'Ipiales','department_id'=>52],
            ['id'=>741,'name'=>'La Cruz','department_id'=>52],
            ['id'=>742,'name'=>'La Florida','department_id'=>52],
            ['id'=>743,'name'=>'La Llanada','department_id'=>52],
            ['id'=>744,'name'=>'La Tola','department_id'=>52],
            ['id'=>745,'name'=>'La Union','department_id'=>52],
            ['id'=>746,'name'=>'Leiva','department_id'=>52],
            ['id'=>747,'name'=>'Linares','department_id'=>52],
            ['id'=>748,'name'=>'Los Andes','department_id'=>52],
            ['id'=>749,'name'=>'Magüi','department_id'=>52],
            ['id'=>750,'name'=>'Mallama','department_id'=>52],
            ['id'=>751,'name'=>'Mosquera','department_id'=>52],
            ['id'=>752,'name'=>'Nariño','department_id'=>52],
            ['id'=>753,'name'=>'Olaya Herrera','department_id'=>52],
            ['id'=>754,'name'=>'Ospina','department_id'=>52],
            ['id'=>755,'name'=>'Francisco Pizarro','department_id'=>52],
            ['id'=>756,'name'=>'Policarpa','department_id'=>52],
            ['id'=>757,'name'=>'Potosi','department_id'=>52],
            ['id'=>758,'name'=>'Providencia','department_id'=>52],
            ['id'=>759,'name'=>'Puerres','department_id'=>52],
            ['id'=>760,'name'=>'Pupiales','department_id'=>52],
            ['id'=>761,'name'=>'Ricaurte','department_id'=>52],
            ['id'=>762,'name'=>'Roberto Payan','department_id'=>52],
            ['id'=>763,'name'=>'Samaniego','department_id'=>52],
            ['id'=>764,'name'=>'Sandona','department_id'=>52],
            ['id'=>765,'name'=>'San Bernardo','department_id'=>52],
            ['id'=>766,'name'=>'San Lorenzo','department_id'=>52],
            ['id'=>767,'name'=>'San Pablo','department_id'=>52],
            ['id'=>768,'name'=>'San Pedro De Cartago','department_id'=>52],
            ['id'=>769,'name'=>'Santa Barbara','department_id'=>52],
            ['id'=>770,'name'=>'Santacruz','department_id'=>52],
            ['id'=>771,'name'=>'Sapuyes','department_id'=>52],
            ['id'=>772,'name'=>'Taminango','department_id'=>52],
            ['id'=>773,'name'=>'Tangua','department_id'=>52],
            ['id'=>774,'name'=>'Tumaco','department_id'=>52],
            ['id'=>775,'name'=>'Tuquerres','department_id'=>52],
            ['id'=>776,'name'=>'Yacuanquer','department_id'=>52],
            ['id'=>777,'name'=>'Cucuta','department_id'=>54],
            ['id'=>778,'name'=>'Abrego','department_id'=>54],
            ['id'=>779,'name'=>'Arboledas','department_id'=>54],
            ['id'=>780,'name'=>'Bochalema','department_id'=>54],
            ['id'=>781,'name'=>'Bucarasica','department_id'=>54],
            ['id'=>782,'name'=>'Cacota','department_id'=>54],
            ['id'=>783,'name'=>'Cachira','department_id'=>54],
            ['id'=>784,'name'=>'Chinacota','department_id'=>54],
            ['id'=>785,'name'=>'Chitaga','department_id'=>54],
            ['id'=>786,'name'=>'Convencion','department_id'=>54],
            ['id'=>787,'name'=>'Cucutilla','department_id'=>54],
            ['id'=>788,'name'=>'Durania','department_id'=>54],
            ['id'=>789,'name'=>'El Carmen','department_id'=>54],
            ['id'=>790,'name'=>'El Tarra','department_id'=>54],
            ['id'=>791,'name'=>'El Zulia','department_id'=>54],
            ['id'=>792,'name'=>'Gramalote','department_id'=>54],
            ['id'=>793,'name'=>'Hacari','department_id'=>54],
            ['id'=>794,'name'=>'Herran','department_id'=>54],
            ['id'=>795,'name'=>'Labateca','department_id'=>54],
            ['id'=>796,'name'=>'La Esperanza','department_id'=>54],
            ['id'=>797,'name'=>'La Playa','department_id'=>54],
            ['id'=>798,'name'=>'Los Patios','department_id'=>54],
            ['id'=>799,'name'=>'Lourdes','department_id'=>54],
            ['id'=>800,'name'=>'Mutiscua','department_id'=>54],
            ['id'=>801,'name'=>'Ocaña','department_id'=>54],
            ['id'=>802,'name'=>'Pamplona','department_id'=>54],
            ['id'=>803,'name'=>'Pamplonita','department_id'=>54],
            ['id'=>804,'name'=>'Puerto Santander','department_id'=>54],
            ['id'=>805,'name'=>'Ragonvalia','department_id'=>54],
            ['id'=>806,'name'=>'Salazar','department_id'=>54],
            ['id'=>807,'name'=>'San Calixto','department_id'=>54],
            ['id'=>808,'name'=>'San Cayetano','department_id'=>54],
            ['id'=>809,'name'=>'Santiago','department_id'=>54],
            ['id'=>810,'name'=>'Sardinata','department_id'=>54],
            ['id'=>811,'name'=>'Silos','department_id'=>54],
            ['id'=>812,'name'=>'Teorama','department_id'=>54],
            ['id'=>813,'name'=>'Tibu','department_id'=>54],
            ['id'=>814,'name'=>'Toledo','department_id'=>54],
            ['id'=>815,'name'=>'Villa Caro','department_id'=>54],
            ['id'=>816,'name'=>'Villa Del Rosario','department_id'=>54],
            ['id'=>817,'name'=>'Armenia','department_id'=>63],
            ['id'=>818,'name'=>'Buenavista','department_id'=>63],
            ['id'=>819,'name'=>'Calarca','department_id'=>63],
            ['id'=>820,'name'=>'Circasia','department_id'=>63],
            ['id'=>821,'name'=>'Cordoba','department_id'=>63],
            ['id'=>822,'name'=>'Filandia','department_id'=>63],
            ['id'=>823,'name'=>'Genova','department_id'=>63],
            ['id'=>824,'name'=>'La Tebaida','department_id'=>63],
            ['id'=>825,'name'=>'Montenegro','department_id'=>63],
            ['id'=>826,'name'=>'Pijao','department_id'=>63],
            ['id'=>827,'name'=>'Quimbaya','department_id'=>63],
            ['id'=>828,'name'=>'Salento','department_id'=>63],
            ['id'=>829,'name'=>'Pereira','department_id'=>66],
            ['id'=>830,'name'=>'Apia','department_id'=>66],
            ['id'=>831,'name'=>'Balboa','department_id'=>66],
            ['id'=>832,'name'=>'Belen De Umbria','department_id'=>66],
            ['id'=>833,'name'=>'Dosquebradas','department_id'=>66],
            ['id'=>834,'name'=>'Guatica','department_id'=>66],
            ['id'=>835,'name'=>'La Celia','department_id'=>66],
            ['id'=>836,'name'=>'La Virginia','department_id'=>66],
            ['id'=>837,'name'=>'Marsella','department_id'=>66],
            ['id'=>838,'name'=>'Mistrato','department_id'=>66],
            ['id'=>839,'name'=>'Pueblo Rico','department_id'=>66],
            ['id'=>840,'name'=>'Quinchia','department_id'=>66],
            ['id'=>841,'name'=>'Santa Rosa De Cabal','department_id'=>66],
            ['id'=>842,'name'=>'Santuario','department_id'=>66],
            ['id'=>843,'name'=>'Bucaramanga','department_id'=>68],
            ['id'=>844,'name'=>'Aguada','department_id'=>68],
            ['id'=>845,'name'=>'Albania','department_id'=>68],
            ['id'=>846,'name'=>'Aratoca','department_id'=>68],
            ['id'=>847,'name'=>'Barbosa','department_id'=>68],
            ['id'=>848,'name'=>'Barichara','department_id'=>68],
            ['id'=>849,'name'=>'Barrancabermeja','department_id'=>68],
            ['id'=>850,'name'=>'Betulia','department_id'=>68],
            ['id'=>851,'name'=>'Bolivar','department_id'=>68],
            ['id'=>852,'name'=>'Cabrera','department_id'=>68],
            ['id'=>853,'name'=>'California','department_id'=>68],
            ['id'=>854,'name'=>'Capitanejo','department_id'=>68],
            ['id'=>855,'name'=>'Carcasi','department_id'=>68],
            ['id'=>856,'name'=>'Cepita','department_id'=>68],
            ['id'=>857,'name'=>'Cerrito','department_id'=>68],
            ['id'=>858,'name'=>'Charala','department_id'=>68],
            ['id'=>859,'name'=>'Charta','department_id'=>68],
            ['id'=>860,'name'=>'Chima','department_id'=>68],
            ['id'=>861,'name'=>'Chipata','department_id'=>68],
            ['id'=>862,'name'=>'Cimitarra','department_id'=>68],
            ['id'=>863,'name'=>'Concepcion','department_id'=>68],
            ['id'=>864,'name'=>'Confines','department_id'=>68],
            ['id'=>865,'name'=>'Contratacion','department_id'=>68],
            ['id'=>866,'name'=>'Coromoro','department_id'=>68],
            ['id'=>867,'name'=>'Curiti','department_id'=>68],
            ['id'=>868,'name'=>'El Carmen De Chucuri','department_id'=>68],
            ['id'=>869,'name'=>'El Guacamayo','department_id'=>68],
            ['id'=>870,'name'=>'El Peñon','department_id'=>68],
            ['id'=>871,'name'=>'El Playon','department_id'=>68],
            ['id'=>872,'name'=>'Encino','department_id'=>68],
            ['id'=>873,'name'=>'Enciso','department_id'=>68],
            ['id'=>874,'name'=>'Florian','department_id'=>68],
            ['id'=>875,'name'=>'Floridablanca','department_id'=>68],
            ['id'=>876,'name'=>'Galan','department_id'=>68],
            ['id'=>877,'name'=>'Gambita','department_id'=>68],
            ['id'=>878,'name'=>'Giron','department_id'=>68],
            ['id'=>879,'name'=>'Guaca','department_id'=>68],
            ['id'=>880,'name'=>'Guadalupe','department_id'=>68],
            ['id'=>881,'name'=>'Guapota','department_id'=>68],
            ['id'=>882,'name'=>'Guavata','department_id'=>68],
            ['id'=>883,'name'=>'Güepsa','department_id'=>68],
            ['id'=>884,'name'=>'Hato','department_id'=>68],
            ['id'=>885,'name'=>'Jesus Maria','department_id'=>68],
            ['id'=>886,'name'=>'Jordan','department_id'=>68],
            ['id'=>887,'name'=>'La Belleza','department_id'=>68],
            ['id'=>888,'name'=>'Landazuri','department_id'=>68],
            ['id'=>889,'name'=>'La Paz','department_id'=>68],
            ['id'=>890,'name'=>'Lebrija','department_id'=>68],
            ['id'=>891,'name'=>'Los Santos','department_id'=>68],
            ['id'=>892,'name'=>'Macaravita','department_id'=>68],
            ['id'=>893,'name'=>'Malaga','department_id'=>68],
            ['id'=>894,'name'=>'Matanza','department_id'=>68],
            ['id'=>895,'name'=>'Mogotes','department_id'=>68],
            ['id'=>896,'name'=>'Molagavita','department_id'=>68],
            ['id'=>897,'name'=>'Ocamonte','department_id'=>68],
            ['id'=>898,'name'=>'Oiba','department_id'=>68],
            ['id'=>899,'name'=>'Onzaga','department_id'=>68],
            ['id'=>900,'name'=>'Palmar','department_id'=>68],
            ['id'=>901,'name'=>'Palmas Del Socorro','department_id'=>68],
            ['id'=>902,'name'=>'Paramo','department_id'=>68],
            ['id'=>903,'name'=>'Piedecuesta','department_id'=>68],
            ['id'=>904,'name'=>'Pinchote','department_id'=>68],
            ['id'=>905,'name'=>'Puente Nacional','department_id'=>68],
            ['id'=>906,'name'=>'Puerto Parra','department_id'=>68],
            ['id'=>907,'name'=>'Puerto Wilches','department_id'=>68],
            ['id'=>908,'name'=>'Rionegro','department_id'=>68],
            ['id'=>909,'name'=>'Sabana De Torres','department_id'=>68],
            ['id'=>910,'name'=>'San Andres','department_id'=>68],
            ['id'=>911,'name'=>'San Benito','department_id'=>68],
            ['id'=>912,'name'=>'San Gil','department_id'=>68],
            ['id'=>913,'name'=>'San Joaquin','department_id'=>68],
            ['id'=>914,'name'=>'San Jose De Miranda','department_id'=>68],
            ['id'=>915,'name'=>'San Miguel','department_id'=>68],
            ['id'=>916,'name'=>'San Vicente De Chucuri','department_id'=>68],
            ['id'=>917,'name'=>'Santa Barbara','department_id'=>68],
            ['id'=>918,'name'=>'Santa Helena Del Opon','department_id'=>68],
            ['id'=>919,'name'=>'Simacota','department_id'=>68],
            ['id'=>920,'name'=>'Socorro','department_id'=>68],
            ['id'=>921,'name'=>'Suaita','department_id'=>68],
            ['id'=>922,'name'=>'Sucre','department_id'=>68],
            ['id'=>923,'name'=>'Surata','department_id'=>68],
            ['id'=>924,'name'=>'Tona','department_id'=>68],
            ['id'=>925,'name'=>'Valle De San Jose','department_id'=>68],
            ['id'=>926,'name'=>'Velez','department_id'=>68],
            ['id'=>927,'name'=>'Vetas','department_id'=>68],
            ['id'=>928,'name'=>'Villanueva','department_id'=>68],
            ['id'=>929,'name'=>'Zapatoca','department_id'=>68],
            ['id'=>930,'name'=>'Sincelejo','department_id'=>70],
            ['id'=>931,'name'=>'Buenavista','department_id'=>70],
            ['id'=>932,'name'=>'Caimito','department_id'=>70],
            ['id'=>933,'name'=>'Coloso','department_id'=>70],
            ['id'=>934,'name'=>'Corozal','department_id'=>70],
            ['id'=>935,'name'=>'Chalan','department_id'=>70],
            ['id'=>936,'name'=>'El Roble','department_id'=>70],
            ['id'=>937,'name'=>'Galeras','department_id'=>70],
            ['id'=>938,'name'=>'Guaranda','department_id'=>70],
            ['id'=>939,'name'=>'La Union','department_id'=>70],
            ['id'=>940,'name'=>'Los Palmitos','department_id'=>70],
            ['id'=>941,'name'=>'Majagual','department_id'=>70],
            ['id'=>942,'name'=>'Morroa','department_id'=>70],
            ['id'=>943,'name'=>'Ovejas','department_id'=>70],
            ['id'=>944,'name'=>'Palmito','department_id'=>70],
            ['id'=>945,'name'=>'Sampues','department_id'=>70],
            ['id'=>946,'name'=>'San Benito Abad','department_id'=>70],
            ['id'=>947,'name'=>'San Juan De Betulia','department_id'=>70],
            ['id'=>948,'name'=>'San Marcos','department_id'=>70],
            ['id'=>949,'name'=>'San Onofre','department_id'=>70],
            ['id'=>950,'name'=>'San Pedro','department_id'=>70],
            ['id'=>951,'name'=>'Since','department_id'=>70],
            ['id'=>952,'name'=>'Sucre','department_id'=>70],
            ['id'=>953,'name'=>'Santiago De Tolu','department_id'=>70],
            ['id'=>954,'name'=>'Toluviejo','department_id'=>70],
            ['id'=>955,'name'=>'Ibague','department_id'=>73],
            ['id'=>956,'name'=>'Alpujarra','department_id'=>73],
            ['id'=>957,'name'=>'Alvarado','department_id'=>73],
            ['id'=>958,'name'=>'Ambalema','department_id'=>73],
            ['id'=>959,'name'=>'Anzoategui','department_id'=>73],
            ['id'=>960,'name'=>'Armero','department_id'=>73],
            ['id'=>961,'name'=>'Ataco','department_id'=>73],
            ['id'=>962,'name'=>'Cajamarca','department_id'=>73],
            ['id'=>963,'name'=>'Carmen De Apicala','department_id'=>73],
            ['id'=>964,'name'=>'Casabianca','department_id'=>73],
            ['id'=>965,'name'=>'Chaparral','department_id'=>73],
            ['id'=>966,'name'=>'Coello','department_id'=>73],
            ['id'=>967,'name'=>'Coyaima','department_id'=>73],
            ['id'=>968,'name'=>'Cunday','department_id'=>73],
            ['id'=>969,'name'=>'Dolores','department_id'=>73],
            ['id'=>970,'name'=>'Espinal','department_id'=>73],
            ['id'=>971,'name'=>'Falan','department_id'=>73],
            ['id'=>972,'name'=>'Flandes','department_id'=>73],
            ['id'=>973,'name'=>'Fresno','department_id'=>73],
            ['id'=>974,'name'=>'Guamo','department_id'=>73],
            ['id'=>975,'name'=>'Herveo','department_id'=>73],
            ['id'=>976,'name'=>'Honda','department_id'=>73],
            ['id'=>977,'name'=>'Icononzo','department_id'=>73],
            ['id'=>978,'name'=>'Lerida','department_id'=>73],
            ['id'=>979,'name'=>'Libano','department_id'=>73],
            ['id'=>980,'name'=>'Mariquita','department_id'=>73],
            ['id'=>981,'name'=>'Melgar','department_id'=>73],
            ['id'=>982,'name'=>'Murillo','department_id'=>73],
            ['id'=>983,'name'=>'Natagaima','department_id'=>73],
            ['id'=>984,'name'=>'Ortega','department_id'=>73],
            ['id'=>985,'name'=>'Palocabildo','department_id'=>73],
            ['id'=>986,'name'=>'Piedras','department_id'=>73],
            ['id'=>987,'name'=>'Planadas','department_id'=>73],
            ['id'=>988,'name'=>'Prado','department_id'=>73],
            ['id'=>989,'name'=>'Purificacion','department_id'=>73],
            ['id'=>990,'name'=>'Rioblanco','department_id'=>73],
            ['id'=>991,'name'=>'Roncesvalles','department_id'=>73],
            ['id'=>992,'name'=>'Rovira','department_id'=>73],
            ['id'=>993,'name'=>'Saldaña','department_id'=>73],
            ['id'=>994,'name'=>'San Antonio','department_id'=>73],
            ['id'=>995,'name'=>'San Luis','department_id'=>73],
            ['id'=>996,'name'=>'Santa Isabel','department_id'=>73],
            ['id'=>997,'name'=>'Suarez','department_id'=>73],
            ['id'=>998,'name'=>'Valle De San Juan','department_id'=>73],
            ['id'=>999,'name'=>'Venadillo','department_id'=>73],
            ['id'=>1000,'name'=>'Villahermosa','department_id'=>73],
            ['id'=>1001,'name'=>'Villarrica','department_id'=>73],
            ['id'=>1002,'name'=>'Cali','department_id'=>76],
            ['id'=>1003,'name'=>'Alcala','department_id'=>76],
            ['id'=>1004,'name'=>'Andalucia','department_id'=>76],
            ['id'=>1005,'name'=>'Ansermanuevo','department_id'=>76],
            ['id'=>1006,'name'=>'Argelia','department_id'=>76],
            ['id'=>1007,'name'=>'Bolivar','department_id'=>76],
            ['id'=>1008,'name'=>'Buenaventura','department_id'=>76],
            ['id'=>1009,'name'=>'Guadalajara De Buga','department_id'=>76],
            ['id'=>1010,'name'=>'Bugalagrande','department_id'=>76],
            ['id'=>1011,'name'=>'Caicedonia','department_id'=>76],
            ['id'=>1012,'name'=>'Calima','department_id'=>76],
            ['id'=>1013,'name'=>'Candelaria','department_id'=>76],
            ['id'=>1014,'name'=>'Cartago','department_id'=>76],
            ['id'=>1015,'name'=>'Dagua','department_id'=>76],
            ['id'=>1016,'name'=>'El Aguila','department_id'=>76],
            ['id'=>1017,'name'=>'El Cairo','department_id'=>76],
            ['id'=>1018,'name'=>'El Cerrito','department_id'=>76],
            ['id'=>1019,'name'=>'El Dovio','department_id'=>76],
            ['id'=>1020,'name'=>'Florida','department_id'=>76],
            ['id'=>1021,'name'=>'Ginebra','department_id'=>76],
            ['id'=>1022,'name'=>'Guacari','department_id'=>76],
            ['id'=>1023,'name'=>'Jamundi','department_id'=>76],
            ['id'=>1024,'name'=>'La Cumbre','department_id'=>76],
            ['id'=>1025,'name'=>'La Union','department_id'=>76],
            ['id'=>1026,'name'=>'La Victoria','department_id'=>76],
            ['id'=>1027,'name'=>'Obando','department_id'=>76],
            ['id'=>1028,'name'=>'Palmira','department_id'=>76],
            ['id'=>1029,'name'=>'Pradera','department_id'=>76],
            ['id'=>1030,'name'=>'Restrepo','department_id'=>76],
            ['id'=>1031,'name'=>'Riofrio','department_id'=>76],
            ['id'=>1032,'name'=>'Roldanillo','department_id'=>76],
            ['id'=>1033,'name'=>'San Pedro','department_id'=>76],
            ['id'=>1034,'name'=>'Sevilla','department_id'=>76],
            ['id'=>1035,'name'=>'Toro','department_id'=>76],
            ['id'=>1036,'name'=>'Trujillo','department_id'=>76],
            ['id'=>1037,'name'=>'Tulua','department_id'=>76],
            ['id'=>1038,'name'=>'Ulloa','department_id'=>76],
            ['id'=>1039,'name'=>'Versalles','department_id'=>76],
            ['id'=>1040,'name'=>'Vijes','department_id'=>76],
            ['id'=>1041,'name'=>'Yotoco','department_id'=>76],
            ['id'=>1042,'name'=>'Yumbo','department_id'=>76],
            ['id'=>1043,'name'=>'Zarzal','department_id'=>76],
            ['id'=>1044,'name'=>'Arauca','department_id'=>81],
            ['id'=>1045,'name'=>'Arauquita','department_id'=>81],
            ['id'=>1046,'name'=>'Cravo Norte','department_id'=>81],
            ['id'=>1047,'name'=>'Fortul','department_id'=>81],
            ['id'=>1048,'name'=>'Puerto Rondon','department_id'=>81],
            ['id'=>1049,'name'=>'Saravena','department_id'=>81],
            ['id'=>1050,'name'=>'Tame','department_id'=>81],
            ['id'=>1051,'name'=>'Yopal','department_id'=>85],
            ['id'=>1052,'name'=>'Aguazul','department_id'=>85],
            ['id'=>1053,'name'=>'Chameza','department_id'=>85],
            ['id'=>1054,'name'=>'Hato Corozal','department_id'=>85],
            ['id'=>1055,'name'=>'La Salina','department_id'=>85],
            ['id'=>1056,'name'=>'Mani','department_id'=>85],
            ['id'=>1057,'name'=>'Monterrey','department_id'=>85],
            ['id'=>1058,'name'=>'Nunchia','department_id'=>85],
            ['id'=>1059,'name'=>'Orocue','department_id'=>85],
            ['id'=>1060,'name'=>'Paz De Ariporo','department_id'=>85],
            ['id'=>1061,'name'=>'Pore','department_id'=>85],
            ['id'=>1062,'name'=>'Recetor','department_id'=>85],
            ['id'=>1063,'name'=>'Sabanalarga','department_id'=>85],
            ['id'=>1064,'name'=>'Sacama','department_id'=>85],
            ['id'=>1065,'name'=>'San Luis De Palenque','department_id'=>85],
            ['id'=>1066,'name'=>'Tamara','department_id'=>85],
            ['id'=>1067,'name'=>'Tauramena','department_id'=>85],
            ['id'=>1068,'name'=>'Trinidad','department_id'=>85],
            ['id'=>1069,'name'=>'Villanueva','department_id'=>85],
            ['id'=>1070,'name'=>'Mocoa','department_id'=>86],
            ['id'=>1071,'name'=>'Colon','department_id'=>86],
            ['id'=>1072,'name'=>'Orito','department_id'=>86],
            ['id'=>1073,'name'=>'Puerto Asis','department_id'=>86],
            ['id'=>1074,'name'=>'Puerto Caicedo','department_id'=>86],
            ['id'=>1075,'name'=>'Puerto Guzman','department_id'=>86],
            ['id'=>1076,'name'=>'Leguizamo','department_id'=>86],
            ['id'=>1077,'name'=>'Sibundoy','department_id'=>86],
            ['id'=>1078,'name'=>'San Francisco','department_id'=>86],
            ['id'=>1079,'name'=>'San Miguel','department_id'=>86],
            ['id'=>1080,'name'=>'Santiago','department_id'=>86],
            ['id'=>1081,'name'=>'Valle Del Guamuez','department_id'=>86],
            ['id'=>1082,'name'=>'Villagarzon','department_id'=>86],
            ['id'=>1083,'name'=>'San Andres','department_id'=>88],
            ['id'=>1084,'name'=>'Providencia','department_id'=>88],
            ['id'=>1085,'name'=>'Leticia','department_id'=>91],
            ['id'=>1086,'name'=>'El Encanto','department_id'=>91],
            ['id'=>1087,'name'=>'La Chorrera','department_id'=>91],
            ['id'=>1088,'name'=>'La Pedrera','department_id'=>91],
            ['id'=>1089,'name'=>'La Victoria','department_id'=>91],
            ['id'=>1090,'name'=>'Miriti - Parana','department_id'=>91],
            ['id'=>1091,'name'=>'Puerto Alegria','department_id'=>91],
            ['id'=>1092,'name'=>'Puerto Arica','department_id'=>91],
            ['id'=>1093,'name'=>'Puerto Nariño','department_id'=>91],
            ['id'=>1094,'name'=>'Puerto Santander','department_id'=>91],
            ['id'=>1095,'name'=>'Tarapaca','department_id'=>91],
            ['id'=>1096,'name'=>'Inirida','department_id'=>94],
            ['id'=>1097,'name'=>'Barranco Minas','department_id'=>94],
            ['id'=>1098,'name'=>'Mapiripana','department_id'=>94],
            ['id'=>1099,'name'=>'San Felipe','department_id'=>94],
            ['id'=>1100,'name'=>'Puerto Colombia','department_id'=>94],
            ['id'=>1101,'name'=>'La Guadalupe','department_id'=>94],
            ['id'=>1102,'name'=>'Cacahual','department_id'=>94],
            ['id'=>1103,'name'=>'Pana Pana','department_id'=>94],
            ['id'=>1104,'name'=>'Morichal','department_id'=>94],
            ['id'=>1105,'name'=>'San Jose Del Guaviare','department_id'=>95],
            ['id'=>1106,'name'=>'Calamar','department_id'=>95],
            ['id'=>1107,'name'=>'El Retorno','department_id'=>95],
            ['id'=>1108,'name'=>'Miraflores','department_id'=>95],
            ['id'=>1109,'name'=>'Mitu','department_id'=>97],
            ['id'=>1110,'name'=>'Caruru','department_id'=>97],
            ['id'=>1111,'name'=>'Pacoa','department_id'=>97],
            ['id'=>1112,'name'=>'Taraira','department_id'=>97],
            ['id'=>1113,'name'=>'Papunaua','department_id'=>97],
            ['id'=>1114,'name'=>'Yavarate','department_id'=>97],
            ['id'=>1115,'name'=>'Puerto Carreño','department_id'=>99],
            ['id'=>1116,'name'=>'La Primavera','department_id'=>99],
            ['id'=>1117,'name'=>'Santa Rosalia','department_id'=>99],
            ['id'=>1118,'name'=>'Cumaribo','department_id'=>99],

        ];
        foreach ($muninicipalities as $municipality) {
            $aux = new City();
            $aux->id= $municipality['id'];
            $aux->name = $municipality['name'];
            $aux->department_id = $municipality['department_id'];
            $aux->save();
        }
    }
}
